### GENERAL SETTINGS ###

# Site settings
title: 
description: 
baseurl: "" #important: start with /
url: "http://emergencesound.com"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#d8c58f" #"#F70031"
  primary_rgb: "216,197,143" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#000000" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: soundcloud
    url: https://soundcloud.com/jim-yates
  - title: facebook
    url: https://www.facebook.com/emergencesound
  - title: twitter
    url: https://twitter.com/EmergenceSound

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - 11 N Serenity Way
    - Greenwood, IN 46142
    - United States
email: james.yates3@gmail.com
tel: 1 (317) 460-1729


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Jim Yates
    position: Owner and Lead Engineer
    img: jim.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle